"""Embed Fabio Crameri's Scientific colour maps (v8.0) in the viewer page as 256-step LUTs.

Source: the colour-map tables shipped in the `cmcrameri` package (MIT; colour maps © 2020 Fabio
Crameri). Point --src at its `cmaps` folder. Rewrites the block between the CRAMERI-LUTS markers
in src/mesc_io/viewer.html; nothing else is touched.

Cite: Crameri, F. (2018). Scientific colour maps. Zenodo. https://doi.org/10.5281/zenodo.1243862

    python tools/gen_crameri_luts.py --src /path/to/cmcrameri/cmaps
"""
import argparse
from pathlib import Path

SEQUENTIAL = ["batlow", "batlowK", "batlowW", "acton", "bamako", "bilbao", "buda", "davos", "devon", "grayC",
              "hawaii", "imola", "lajolla", "lapaz", "lipari", "navia", "nuuk", "oslo", "tokyo", "turku"]
DIVERGING = ["berlin", "vik", "roma", "managua", "vanimo"]
PAGE = Path(__file__).resolve().parents[1] / "src" / "mesc_io" / "viewer.html"
BEGIN, END = "/* CRAMERI-LUTS:BEGIN", "/* CRAMERI-LUTS:END */"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", required=True)
    a = ap.parse_args()
    lines = []
    for name in SEQUENTIAL + DIVERGING:
        rows = [l.split() for l in open(Path(a.src) / f"{name}.txt") if l.strip()]
        assert len(rows) == 256, f"{name}: {len(rows)} rows"
        hexs = "".join("%02x%02x%02x" % tuple(round(float(v) * 255) for v in r) for r in rows)
        lines.append(f'  {name}: "{hexs}",')
    block = (f"{BEGIN} — Scientific colour maps v8.0, (c) 2020 Fabio Crameri, MIT licence\n"
             "   (third_party/crameri_LICENSE.txt). Cite: Crameri, F. (2018). Scientific colour maps.\n"
             "   Zenodo. https://doi.org/10.5281/zenodo.1243862 — generated by tools/gen_crameri_luts.py */\n"
             "const CRAMERI = {\n" + "\n".join(lines) + "\n};\n"
             f"const CRAMERI_SEQ = {SEQUENTIAL!r}, CRAMERI_DIV = {DIVERGING!r};\n" + END)
    s = PAGE.read_text()
    i, j = s.index(BEGIN), s.index(END) + len(END)
    PAGE.write_text(s[:i] + block + s[j:])
    print(f"{len(lines)} maps written into {PAGE.name}")


if __name__ == "__main__":
    main()
